name: flutter_razorpay_wrapper
description: Flutter plugin for Razorpay SDK. To know more about Razorpay, visit http://razorpay.com.
version: 1.0.1
homepage: https://github.com/Jawahar112/flutter_razorpay_wrapper

environment:
  sdk: ^3.6.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  eventify: ^1.0.1
  js: ^0.6.7
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.razorpay.razorpay_flutter
        pluginClass: RazorpayFlutterPlugin
      ios:
        pluginClass: RazorpayFlutterPlugin
      web:
        pluginClass: RazorpayFlutterPlugin
        fileName: razorpay_flutter_plugin.dart
